import React from 'react';
import type { ComponentType } from 'react';
import type { StyleProp, ViewStyle } from 'react-native';
import {
  Search,
  User,
  Heart,
  ShoppingCart,
  Bell,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  Plus,
  Minus,
  Check,
  X,
  Star,
  MapPin,
  Clock,
  Truck,
  Filter,
  SlidersHorizontal,
  ArrowRight,
  ArrowLeft,
  CreditCard,
  Wallet,
  Tag,
  Percent,
  Flame,
  Package,
  ReceiptText,
  Settings,
  LogOut,
  Phone,
  Mail,
  Navigation,
  Sparkles,
  ThumbsUp,
  MessageCircle,
  Gift,
  Ticket,
  Store,
  ShieldCheck,
  Zap,
  Leaf,
  PlusCircle,
  MoreHorizontal,
  Trash2,
  Edit,
  RotateCcw,
  Frown,
  ShoppingBag,
  Coffee,
  Pizza,
  Salad,
  Soup,
  Beef,
  Fish,
  IceCream,
  Croissant,
  Cake,
  Carrot,
  Cookie,
  Sandwich,
  CupSoda,
  Apple,
  Shirt,
  Watch,
  Smartphone,
  Headphones,
  Laptop,
  Home,
  BookOpen,
  Dumbbell,
  Sofa,
  Gem,
  Gamepad2,
  Camera,
  ScanLine,
  CircleCheck,
  CalendarClock,
  LocateFixed,
  IndianRupee,
  UtensilsCrossed,
  ChefHat,
  ArrowUpRight,
  Info,
  Bike,
  Timer,
  Send,
  UserRound,
  QrCode,
  Repeat,
  BadgeCheck,
  Gauge,
  TrendingUp,
  BadgePercent,
  Eye,
  Lock,
  MapPinned,
  CornerDownLeft,
  Image as ImageIcon,
  ChevronsUpDown,
  ArrowUpDown,
  CircleAlert,
  Share as ShareIcon,
} from 'lucide-react-native';

export type IconType = ComponentType<{
  size?: number;
  color?: string;
  fill?: string;
  strokeWidth?: number | string;
  style?: StyleProp<ViewStyle>;
}>;

const registry = {
  search: Search,
  user: User,
  userRound: UserRound,
  heart: Heart,
  cart: ShoppingCart,
  bell: Bell,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronDown: ChevronDown,
  plus: Plus,
  minus: Minus,
  check: Check,
  circleCheck: CircleCheck,
  x: X,
  star: Star,
  mapPin: MapPin,
  mapPinned: MapPinned,
  clock: Clock,
  timer: Timer,
  truck: Truck,
  bike: Bike,
  filter: Filter,
  sliders: SlidersHorizontal,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  arrowUpRight: ArrowUpRight,
  creditCard: CreditCard,
  wallet: Wallet,
  tag: Tag,
  percent: Percent,
  badgePercent: BadgePercent,
  flame: Flame,
  package: Package,
  receipt: ReceiptText,
  settings: Settings,
  logout: LogOut,
  phone: Phone,
  mail: Mail,
  navigation: Navigation,
  sparkles: Sparkles,
  thumbsUp: ThumbsUp,
  message: MessageCircle,
  gift: Gift,
  ticket: Ticket,
  store: Store,
  shield: ShieldCheck,
  zap: Zap,
  leaf: Leaf,
  plusCircle: PlusCircle,
  more: MoreHorizontal,
  trash: Trash2,
  edit: Edit,
  refresh: RotateCcw,
  frown: Frown,
  bag: ShoppingBag,
  coffee: Coffee,
  pizza: Pizza,
  salad: Salad,
  soup: Soup,
  beef: Beef,
  fish: Fish,
  iceCream: IceCream,
  croissant: Croissant,
  cake: Cake,
  carrot: Carrot,
  cookie: Cookie,
  sandwich: Sandwich,
  cupSoda: CupSoda,
  apple: Apple,
  shirt: Shirt,
  watch: Watch,
  smartphone: Smartphone,
  headphones: Headphones,
  laptop: Laptop,
  home: Home,
  book: BookOpen,
  dumbbell: Dumbbell,
  sofa: Sofa,
  gem: Gem,
  gamepad: Gamepad2,
  camera: Camera,
  scan: ScanLine,
  qr: QrCode,
  calendar: CalendarClock,
  locate: LocateFixed,
  rupee: IndianRupee,
  utensils: UtensilsCrossed,
  chef: ChefHat,
  info: Info,
  send: Send,
  repeat: Repeat,
  badgeCheck: BadgeCheck,
  gauge: Gauge,
  trending: TrendingUp,
  eye: Eye,
  lock: Lock,
  cornerDownLeft: CornerDownLeft,
  image: ImageIcon,
  chevronsUpDown: ChevronsUpDown,
  arrowUpDown: ArrowUpDown,
  circleAlert: CircleAlert,
  share: ShareIcon,
} satisfies Record<string, IconType>;

export type IconName = keyof typeof registry;

export interface IconProps {
  name: IconName;
  size?: number;
  color?: string;
  fill?: string;
  strokeWidth?: number;
  style?: StyleProp<ViewStyle>;
}

export function Icon({ name, size = 20, color = '#0B1020', fill, strokeWidth = 2, style }: IconProps): React.ReactElement {
  // Exact key lookup + single callable type; the annotation-free registry keeps
  // IconName as a literal union instead of collapsing to `string`.
  const Cmp = registry[name] as IconType;
  return <Cmp size={size} color={color} fill={fill} strokeWidth={strokeWidth} style={style} />;
}
