import React, { useMemo, useState } from 'react';
import { Image, Pressable, StyleSheet, View } from 'react-native';
import { useNavigation } from '@react-navigation/native';
import { Screen } from '@/components/ui/Screen';
import { Text } from '@/components/ui/Text';
import { Input } from '@/components/ui/Input';
import { Button } from '@/components/ui/Button';
import { BackButton } from '@/components/ui/BackButton';
import { Card, SectionTitle, Badge } from '@/components/ui/VendorUI';
import { Icon } from '@/lib/icons';
import { MapSurface } from '@/screens/shared/MapSurface';
import { useVendor } from '@/context/VendorContext';
import { uploadVendorImage, vendorApi } from '@/api/vendor';
import { pickImage } from '@/lib/pickImage';
import { colors } from '@/theme/colors';
import { radius, spacing } from '@/theme/tokens';
import { haptic } from '@/lib/haptics';
import type { VendorDocument } from '@/api/vendor';

const FOOD_TAGS = ['North Indian', 'South Indian', 'Chinese', 'Biryani', 'Bakery', 'Fast food', 'Sweets', 'Beverages'];
const SHOP_TAGS = ['Grocery', 'Fashion', 'Electronics', 'Home', 'Beauty', 'Pharmacy', 'General'];
const TITLES = ['Outlet profile', 'Compliance', 'Payout account', 'Verify documents'];

export function OnboardingScreen(): React.ReactElement {
  const navigation = useNavigation(); const { vendor, setVendor } = useVendor(); const food = vendor?.module === 'food';
  const [step, setStep] = useState(0); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [tags, setTags] = useState(vendor?.cuisines ?? []);
  const [form, setForm] = useState({ outletName: vendor?.outletName ?? '', legalName: vendor?.legalName ?? '', description: vendor?.description ?? '', address: vendor?.address ?? '', landmark: vendor?.landmark ?? '', city: vendor?.city ?? '', pin: vendor?.pin ?? '', pan: vendor?.pan ?? '', gstin: vendor?.gstin ?? '', fssai: vendor?.fssai ?? '', tradeLicense: vendor?.tradeLicense ?? '', open: vendor?.hours?.open ?? '10:00', close: vendor?.hours?.close ?? '22:00', accountName: vendor?.bank?.accountName ?? '', accountNumber: vendor?.bank?.accountNumber ?? '', ifsc: vendor?.bank?.ifsc ?? '', bankName: vendor?.bank?.bankName ?? '', upi: vendor?.bank?.upi ?? '' });
  const set = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const docs = vendor?.documents ?? [];
  const requiredDocs = useMemo(() => food ? ['aadhaar', 'pan', 'gst', 'bank', 'outlet', 'interior', 'fssai', 'menu'] : ['aadhaar', 'pan', 'gst', 'bank', 'outlet', 'interior', 'trade', 'inventory'], [food]);
  const save = async () => {
    setBusy(true); setError('');
    try {
      if (step < 3) {
        const data = await vendorApi.save({ outletName: form.outletName.trim(), legalName: form.legalName.trim(), description: form.description.trim(), address: form.address.trim(), landmark: form.landmark.trim(), city: form.city.trim(), pin: form.pin.trim(), pan: form.pan.trim().toUpperCase(), gstin: form.gstin.trim().toUpperCase(), fssai: form.fssai.trim(), tradeLicense: form.tradeLicense.trim(), cuisines: tags, hours: { open: form.open, close: form.close }, bank: { accountName: form.accountName.trim(), accountNumber: form.accountNumber.trim(), ifsc: form.ifsc.trim().toUpperCase(), bankName: form.bankName.trim(), upi: form.upi.trim() } });
        setVendor(data.vendor); setStep((value) => value + 1); haptic.light();
      } else { const data = await vendorApi.submit(); setVendor(data.vendor); haptic.success(); }
    } catch (e) { setError(e instanceof Error ? e.message : 'Could not save this step.'); haptic.error(); } finally { setBusy(false); }
  };
  const upload = async (doc: VendorDocument) => {
    const picked = await pickImage(); if (!picked) return;
    setBusy(true); setError(''); try { const uploadResult = await uploadVendorImage(picked.blob, picked.name); const data = await vendorApi.setDoc(doc.key, uploadResult.url, doc.label); setVendor(data.vendor); haptic.success(); } catch (e) { setError(e instanceof Error ? e.message : 'Upload failed.'); haptic.error(); } finally { setBusy(false); }
  };
  const savePin = async (lat: number, lng: number) => { setBusy(true); try { const data = await vendorApi.save({ geo: { lat, lng } }); setVendor(data.vendor); setError(''); } catch (e) { setError(e instanceof Error ? e.message : 'Could not save the outlet pin.'); } finally { setBusy(false); } };
  return <Screen keyboardAvoiding headerLeft={<BackButton onPress={() => { if (step > 0) setStep((value) => value - 1); else navigation.goBack(); }} />} title={TITLES[step]} subtitle={`Step ${step + 1} of 4 · ${food ? 'Food kitchen' : 'Shop'}`}>
    <View style={styles.progress}>{TITLES.map((_, index) => <View key={index} style={[styles.progressBar, { backgroundColor: index <= step ? (food ? colors.food : colors.brand[600]) : colors.border }]} />)}</View>
    {step === 0 ? <><Text variant="body" color={colors.textSecondary} style={{ marginBottom: 14 }}>Tell customers what they will find at this outlet. Your pin helps dispatch find you.</Text><Input label="Outlet name" value={form.outletName} onChangeText={(value) => set('outletName', value)} leftIcon="store" placeholder="The name customers see" /><Input label="Legal / GST name" value={form.legalName} onChangeText={(value) => set('legalName', value)} /><Input label={food ? 'About the kitchen' : 'About the shop'} value={form.description} onChangeText={(value) => set('description', value)} multiline placeholder="Short description" /><Input label="Street address" value={form.address} onChangeText={(value) => set('address', value)} leftIcon="mapPin" /><View style={styles.two}><View style={{ flex: 1 }}><Input label="City" value={form.city} onChangeText={(value) => set('city', value)} /></View><View style={{ flex: 1 }}><Input label="PIN" value={form.pin} onChangeText={(value) => set('pin', value)} keyboardType="number-pad" /></View></View><Input label="Landmark (optional)" value={form.landmark} onChangeText={(value) => set('landmark', value)} /><SectionTitle title="Outlet pin" /><Card style={{ padding: 0, overflow: 'hidden' }}><MapSurface editable lat={vendor?.geo?.lat} lng={vendor?.geo?.lng} onChange={(lat, lng) => void savePin(lat, lng)} height={190} /></Card><SectionTitle title={food ? 'Cuisines' : 'Categories'} /><View style={styles.tags}>{(food ? FOOD_TAGS : SHOP_TAGS).map((tag) => { const active = tags.includes(tag); return <Pressable key={tag} onPress={() => setTags((all) => active ? all.filter((item) => item !== tag) : [...all, tag])} style={[styles.tag, active && { backgroundColor: food ? colors.food : colors.brand[600], borderColor: food ? colors.food : colors.brand[600] }]}><Text variant="caption" weight="bold" color={active ? colors.white : colors.textSecondary}>{tag}</Text></Pressable>; })}</View><View style={styles.two}><View style={{ flex: 1 }}><Input label="Opens" value={form.open} onChangeText={(value) => set('open', value)} /></View><View style={{ flex: 1 }}><Input label="Closes" value={form.close} onChangeText={(value) => set('close', value)} /></View></View></> : null}
    {step === 1 ? <><Text variant="body" color={colors.textSecondary} style={{ marginBottom: 16 }}>{food ? 'Food outlets need FSSAI before they can receive a live order.' : 'Share your tax identity and the shop license used at this address.'}</Text><Input label="PAN" value={form.pan} onChangeText={(value) => set('pan', value)} autoCapitalize="characters" leftIcon="badgeCheck" /><Input label="GSTIN (if registered)" value={form.gstin} onChangeText={(value) => set('gstin', value)} autoCapitalize="characters" leftIcon="receipt" />{food ? <Input label="FSSAI license number" value={form.fssai} onChangeText={(value) => set('fssai', value)} leftIcon="shield" /> : <Input label="Trade / shop license" value={form.tradeLicense} onChangeText={(value) => set('tradeLicense', value)} leftIcon="store" />}<Card tone="warm" style={{ marginTop: 4 }}><View style={{ flexDirection: 'row', gap: 9 }}><Icon name="info" size={18} color={colors.warning} /><Text variant="bodySm" color={colors.warning} style={{ flex: 1 }}>Documents are reviewed individually. If one is rejected, you only re-upload that slot.</Text></View></Card></> : null}
    {step === 2 ? <><Text variant="body" color={colors.textSecondary} style={{ marginBottom: 16 }}>This account receives your net settlement after delivered orders. Double-check the IFSC.</Text><Input label="Account holder" value={form.accountName} onChangeText={(value) => set('accountName', value)} leftIcon="user" /><Input label="Account number" value={form.accountNumber} onChangeText={(value) => set('accountNumber', value)} keyboardType="number-pad" leftIcon="creditCard" /><Input label="IFSC" value={form.ifsc} onChangeText={(value) => set('ifsc', value)} autoCapitalize="characters" /><Input label="Bank name" value={form.bankName} onChangeText={(value) => set('bankName', value)} /><Input label="UPI backup (optional)" value={form.upi} onChangeText={(value) => set('upi', value)} leftIcon="wallet" /></> : null}
    {step === 3 ? <><Card tone="warm"><Text variant="title" weight="bold">Upload clear photos</Text><Text variant="bodySm" color={colors.textSecondary} style={{ marginTop: 5 }}>Every slot is required. Tap a slot to choose or replace its photo.</Text></Card><View style={{ marginTop: 14 }}>{docs.map((doc) => <Pressable key={doc.key} onPress={() => void upload(doc)} style={styles.docRow}><View style={styles.docThumb}>{doc.uri ? <Image source={{ uri: doc.uri }} style={styles.docImage} /> : <Icon name="camera" size={21} color={colors.brand[600]} />}</View><View style={{ flex: 1 }}><Text variant="title" weight="semibold">{doc.label}</Text><Text variant="caption" color={doc.verified ? colors.success : doc.uri ? colors.warning : colors.textTertiary}>{doc.verified ? 'Verified' : doc.uri ? 'Uploaded · awaiting review' : 'Required · tap to upload'}</Text></View><Icon name={doc.uri ? 'circleCheck' : 'plus'} size={21} color={doc.uri ? colors.success : colors.textTertiary} /></Pressable>)}</View><Text variant="caption" color={colors.textTertiary} style={{ marginTop: 12 }}>{docs.filter((doc) => Boolean(doc.uri)).length} of {requiredDocs.length} document slots uploaded</Text></> : null}
    {error ? <View style={styles.error}><Icon name="circleAlert" size={17} color={colors.danger} /><Text variant="bodySm" color={colors.danger} style={{ flex: 1 }}>{error}</Text></View> : null}<View style={{ marginTop: 18, gap: 8 }}><Button title={step === 3 ? 'Submit for verification' : 'Save & continue'} loading={busy} onPress={() => void save()} />{step > 0 ? <Button title="Back" variant="ghost" onPress={() => setStep((value) => value - 1)} /> : null}</View>
  </Screen>;
}
const styles = StyleSheet.create({ progress: { flexDirection: 'row', gap: 5, marginBottom: 20 }, progressBar: { flex: 1, height: 5, borderRadius: 5 }, two: { flexDirection: 'row', gap: 10 }, tags: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 4 }, tag: { borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, paddingHorizontal: 11, paddingVertical: 8, borderRadius: radius.pill }, docRow: { minHeight: 76, borderBottomWidth: 1, borderColor: colors.border, flexDirection: 'row', alignItems: 'center', gap: 12 }, docThumb: { width: 52, height: 52, borderRadius: 13, backgroundColor: colors.brand[50], alignItems: 'center', justifyContent: 'center', overflow: 'hidden' }, docImage: { width: 52, height: 52 }, error: { marginTop: 12, padding: 11, backgroundColor: colors.dangerBg, borderRadius: radius.md, flexDirection: 'row', alignItems: 'center', gap: 8 }, });
