import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Alert, Linking, Pressable, StyleSheet, View, type AlertButton } from 'react-native';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Screen } from '@/components/ui/Screen';
import { Text } from '@/components/ui/Text';
import { Button } from '@/components/ui/Button';
import { BackButton } from '@/components/ui/BackButton';
import { Badge, Card, Divider, IconButton, SectionTitle } from '@/components/ui/VendorUI';
import { Icon } from '@/lib/icons';
import { vendorApi, type OrderStatus, type VendorOrder } from '@/api/vendor';
import { colors } from '@/theme/colors';
import { haptic } from '@/lib/haptics';
import type { RootStackParamList } from '@/navigation/types';

type Props = NativeStackScreenProps<RootStackParamList, 'OrderDetail'>; function money(value: number): string { return `₹${Math.round(value).toLocaleString('en-IN')}`; }
const statusInfo: Record<OrderStatus, { label: string; color: string; bg: string }> = { placed: { label: 'New', color: colors.info, bg: colors.infoBg }, confirmed: { label: 'Accepted', color: colors.brand[700], bg: colors.brand[50] }, preparing: { label: 'Preparing', color: colors.warning, bg: colors.warningBg }, out_for_delivery: { label: 'Ready for pickup', color: colors.success, bg: colors.successBg }, delivered: { label: 'Delivered', color: colors.success, bg: colors.successBg }, cancelled: { label: 'Cancelled', color: colors.danger, bg: colors.dangerBg } };
function Timeline({ status }: { status: OrderStatus }): React.ReactElement { const states = ['placed', 'confirmed', 'preparing', 'out_for_delivery', 'delivered']; const current = status === 'cancelled' ? 0 : states.indexOf(status); return <View style={styles.timeline}>{states.map((state, index) => <View key={state} style={styles.timelineRow}><View style={styles.timelineRail}><View style={[styles.dot, { backgroundColor: index <= current ? colors.brand[600] : colors.border }]}>{index <= current ? <Icon name="check" size={11} color={colors.white} /> : null}</View>{index < states.length - 1 ? <View style={[styles.rail, { backgroundColor: index < current ? colors.brand[600] : colors.border }]} /> : null}</View><View style={{ paddingBottom: index < states.length - 1 ? 16 : 0 }}><Text variant="title" weight="bold">{state === 'placed' ? 'Order placed' : state === 'confirmed' ? 'Accepted' : state === 'preparing' ? 'Being prepared' : state === 'out_for_delivery' ? 'Ready for pickup' : 'Delivered'}</Text><Text variant="caption" color={colors.textSecondary}>{index === current ? 'Current status' : index < current ? 'Completed' : 'Waiting'}</Text></View></View>)}</View>; }
export function OrderDetailScreen({ route, navigation }: Props): React.ReactElement { const { orderId } = route.params; const [order, setOrder] = useState<VendorOrder | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [acting, setActing] = useState(false); const load = useCallback(async () => { try { const result = await vendorApi.order(orderId); setOrder(result.order); setError(''); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load order'); } finally { setLoading(false); } }, [orderId]); useEffect(() => { void load(); const timer = setInterval(() => void load(), 15000); return () => clearInterval(timer); }, [load]);
  const act = async (action: () => Promise<{ order: VendorOrder }>) => { setActing(true); try { const result = await action(); setOrder(result.order); haptic.success(); } catch (e) { Alert.alert('Could not update order', e instanceof Error ? e.message : 'Try again'); haptic.error(); } finally { setActing(false); } };
  const reject = () => Alert.alert('Reject order?', 'The customer will be notified. Why can’t you fulfil it?', [{ text: 'Item unavailable', onPress: () => void act(() => vendorApi.reject(orderId, 'item_unavailable', undefined, order?.status)) }, { text: 'Kitchen is busy', onPress: () => void act(() => vendorApi.reject(orderId, 'kitchen_busy', undefined, order?.status)) }, { text: 'Keep order', style: 'cancel' }]);
  const partial = () => { const items = (order?.items ?? []).filter((item) => item.id); if (items.length < 2) return Alert.alert('Partial accept', 'This order does not include enough line IDs. Accept the full order instead.'); const buttons: AlertButton[] = items.slice(0, -1).map((item) => ({ text: `Remove ${item.name}`, style: 'destructive', onPress: () => void act(() => vendorApi.partialAccept(orderId, [item.id as string])) })); buttons.push({ text: 'Cancel', style: 'cancel' }); Alert.alert('Remove an item and accept', 'The customer total will be recalculated.', buttons); };
  const accept = () => { const choices = [10, 15, 20, 30].map((mins) => ({ text: `${mins} minutes`, onPress: () => void act(() => vendorApi.accept(orderId, mins, order?.status)) })); choices.push({ text: 'Cancel', onPress: () => undefined }); Alert.alert('Set prep time', 'Tell the customer when this will be ready.', choices as any); };
  const commission = Number(((order?.itemTotal ?? order?.total ?? 0) * .05).toFixed(2)); const net = (order?.itemTotal ?? order?.total ?? 0) - commission;
  if (loading) return <Screen title="Order details" headerLeft={<BackButton onPress={() => navigation.goBack()} />}><View style={styles.loading}><Text variant="body" color={colors.textSecondary}>Loading ticket…</Text></View></Screen>;
  if (!order) return <Screen title="Order details" headerLeft={<BackButton onPress={() => navigation.goBack()} />}><View style={styles.loading}><Icon name="circleAlert" size={28} color={colors.danger} /><Text variant="body" color={colors.danger} style={{ marginTop: 10 }}>{error || 'Order not found'}</Text><Button title="Try again" variant="secondary" onPress={() => void load()} style={{ marginTop: 18 }} /></View></Screen>;
  const info = statusInfo[order.status]; const customer = order.customer || order.user;
  return <Screen title={`Order #${order.code}`} subtitle={`${customer?.name || 'Customer'} · ${new Date(order.placedAt).toLocaleString('en-IN', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' })}`} headerLeft={<BackButton onPress={() => navigation.goBack()} />} headerRight={<Badge label={info.label} color={info.color} background={info.bg} />}>
    <Card style={styles.hero}><View style={{ flex: 1 }}><Text variant="caption" color={colors.textSecondary}>CUSTOMER</Text><Text variant="h3" weight="bold" style={{ marginTop: 4 }}>{customer?.name || 'Aurasure customer'}</Text><Text variant="caption" color={colors.textSecondary} style={{ marginTop: 3 }}>{order.items.reduce((sum, item) => sum + item.qty, 0)} items · {order.payBy?.toUpperCase() || 'COD'}</Text></View>{customer?.phone ? <IconButton icon="phone" color={colors.success} background={colors.successBg} onPress={() => void Linking.openURL(`tel:${customer.phone}`)} /> : null}</Card>
    <SectionTitle title="Items" /><Card>{order.items.map((item, index) => <React.Fragment key={`${item.name}-${index}`}><View style={styles.item}><View style={styles.qty}><Text variant="caption" weight="bold" color={colors.brand[700]}>{item.qty}×</Text></View><View style={{ flex: 1 }}><Text variant="title" weight="semibold">{item.name}</Text>{item.meta ? <Text variant="caption" color={colors.textSecondary}>{item.meta}</Text> : null}</View><Text variant="title" weight="bold">{money(item.qty * item.unitPrice)}</Text></View>{index < order.items.length - 1 ? <Divider /> : null}</React.Fragment>)}<Divider space={9} /><Bill label="Item total" value={order.itemTotal ?? order.items.reduce((sum, item) => sum + item.qty * item.unitPrice, 0)} /><Bill label="Delivery fee" value={order.deliveryFee ?? 0} /><Bill label="Discount" value={-(order.discount ?? 0)} /><View style={styles.billTotal}><Text variant="title" weight="bold">Customer total</Text><Text variant="h3" weight="bold" color={colors.brand[700]}>{money(order.total)}</Text></View></Card>
    <SectionTitle title="Your settlement" /><Card tone="warm"><Bill label="Gross item value" value={order.itemTotal ?? order.total} /><Bill label="Platform commission · 5%" value={-commission} /><View style={styles.billTotal}><Text variant="title" weight="bold">Your net</Text><Text variant="h2" weight="bold" color={colors.success}>{money(net)}</Text></View></Card>
    {order.instructions ? <><SectionTitle title="Customer instructions" /><Card tone="warm"><View style={{ flexDirection: 'row', gap: 8 }}><Icon name="info" size={17} color={colors.warning} /><Text variant="body" color={colors.warning} style={{ flex: 1 }}>{order.instructions}</Text></View></Card></> : null}
    <SectionTitle title="Delivery" /><Card>{order.address ? <View style={styles.address}><Icon name="mapPin" size={19} color={colors.brand[600]} /><View style={{ flex: 1 }}><Text variant="caption" color={colors.textSecondary}>DELIVERY ADDRESS</Text><Text variant="body" style={{ marginTop: 3 }}>{order.delivery ? order.address : 'Address is shared with the rider after pickup.'}</Text></View></View> : null}{order.delivery ? <><Divider space={12} /><View style={styles.rider}><View style={styles.riderAvatar}><Icon name="bike" size={20} color={colors.brand[700]} /></View><View style={{ flex: 1 }}><Text variant="title" weight="bold">{order.delivery.riderName || 'Rider assigned'}</Text><Text variant="caption" color={colors.textSecondary}>{order.delivery.state.replace(/_/g, ' ')}</Text></View>{order.delivery.riderPhone ? <IconButton icon="phone" color={colors.success} background={colors.successBg} onPress={() => void Linking.openURL(`tel:${order.delivery?.riderPhone}`)} /> : null}</View>{order.delivery.pickupOtp ? <View style={styles.otp}><Text variant="caption" weight="bold" color={colors.brand[700]}>PICKUP OTP</Text><Text variant="h2" weight="extrabold" color={colors.brand[700]} style={{ letterSpacing: 5 }}>{order.delivery.pickupOtp}</Text><Text variant="caption" color={colors.textSecondary}>Share with the rider at handover</Text></View> : null}</> : <Text variant="bodySm" color={colors.textSecondary}>Rider details and pickup OTP appear after the order is ready.</Text>}</Card>
    <SectionTitle title="Status timeline" /><Card><Timeline status={order.status} /></Card>
    {order.status === 'placed' ? <><View style={styles.actions}><Button title="Reject" variant="secondary" size="sm" onPress={reject} style={{ flex: 1 }} /><Button title="Accept order" onPress={accept} size="sm" style={{ flex: 1 }} loading={acting} /></View>{order.payBy === 'cod' ? <Button title="Accept with an item removed" variant="ghost" size="sm" onPress={partial} disabled={acting} /> : null}</> : order.status === 'confirmed' || order.status === 'preparing' ? <Button title="Mark ready for pickup" onPress={() => void act(() => vendorApi.ready(orderId, order.status))} loading={acting} /> : null}
  </Screen>;
}
function Bill({ label, value }: { label: string; value: number }): React.ReactElement { return <View style={styles.bill}><Text variant="bodySm" color={colors.textSecondary}>{label}</Text><Text variant="bodySm" color={value < 0 ? colors.danger : colors.text} weight="semibold">{value < 0 ? '−' : ''}{money(Math.abs(value))}</Text></View>; }
const styles = StyleSheet.create({ hero: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.surfaceWarm }, item: { minHeight: 52, flexDirection: 'row', alignItems: 'center', gap: 9 }, qty: { width: 34, height: 28, borderRadius: 8, backgroundColor: colors.brand[50], alignItems: 'center', justifyContent: 'center' }, bill: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 4 }, billTotal: { borderTopWidth: 1, borderColor: colors.border, marginTop: 8, paddingTop: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, address: { flexDirection: 'row', gap: 9, alignItems: 'flex-start' }, rider: { flexDirection: 'row', alignItems: 'center', gap: 10 }, riderAvatar: { width: 42, height: 42, borderRadius: 14, backgroundColor: colors.brand[50], alignItems: 'center', justifyContent: 'center' }, otp: { alignItems: 'center', backgroundColor: colors.brand[50], borderRadius: 12, padding: 13, marginTop: 14, gap: 3 }, timelineRow: { flexDirection: 'row' }, timelineRail: { width: 30, alignItems: 'center' }, dot: { width: 22, height: 22, borderRadius: 11, alignItems: 'center', justifyContent: 'center' }, rail: { width: 2, minHeight: 23, flex: 1 }, timeline: { paddingVertical: 4 }, actions: { flexDirection: 'row', gap: 8 }, loading: { flex: 1, alignItems: 'center', justifyContent: 'center' } });
