import React, { useState } from 'react';
import { Pressable, StyleSheet, View } from 'react-native';
import { Icon } from '@/lib/icons';
import { Text } from '@/components/ui/Text';
import { colors } from '@/theme/colors';

type Props = { lat?: number | null; lng?: number | null; editable?: boolean; onChange?: (lat: number, lng: number) => void; height?: number };
const DEFAULT = { lat: 22.7196, lng: 75.8577 };
export function MapSurface({ lat, lng, editable = false, onChange, height = 218 }: Props): React.ReactElement { const [point, setPoint] = useState({ lat: lat ?? DEFAULT.lat, lng: lng ?? DEFAULT.lng }); const move = (next: { lat: number; lng: number }) => { setPoint(next); onChange?.(next.lat, next.lng); }; return <Pressable onPress={(event) => { if (!editable) return; const { locationX, locationY } = event.nativeEvent; move({ lat: point.lat + (0.5 - locationY / height) * 0.008, lng: point.lng + (locationX / 320 - 0.5) * 0.012 }); }} style={[styles.map, { height }]}><View style={styles.roadOne} /><View style={styles.roadTwo} /><View style={styles.roadThree} /><View style={styles.park}><Text variant="caption" color="#6E8A67">GREEN BELT</Text></View><View style={styles.pin}><Icon name="mapPin" size={30} color={colors.brand[700]} filled /><View style={styles.pinDot} /></View><View style={styles.mapLabel}><Icon name="mapPinned" size={15} color={colors.brand[700]} /><Text variant="caption" weight="bold" color={colors.brand[700]}>{editable ? 'Tap map to move pin' : 'Outlet location'}</Text></View></Pressable>; }
const styles = StyleSheet.create({ map: { backgroundColor: '#E8E5DF', position: 'relative', overflow: 'hidden' }, roadOne: { position: 'absolute', width: '140%', height: 24, backgroundColor: colors.mapRoad, transform: [{ rotate: '-18deg' }], top: 72, left: -40 }, roadTwo: { position: 'absolute', width: '140%', height: 12, backgroundColor: colors.mapRoad, transform: [{ rotate: '42deg' }], top: 106, left: -20 }, roadThree: { position: 'absolute', width: '100%', height: 8, backgroundColor: colors.mapRoad, top: 162, left: 0 }, park: { position: 'absolute', right: 18, top: 22, width: 82, height: 70, borderRadius: 18, backgroundColor: colors.mapPark, alignItems: 'center', justifyContent: 'center' }, pin: { position: 'absolute', left: '48%', top: '39%', alignItems: 'center' }, pinDot: { width: 9, height: 9, borderRadius: 5, backgroundColor: colors.white, position: 'absolute', top: 10 }, mapLabel: { position: 'absolute', left: 12, bottom: 12, backgroundColor: colors.white, borderRadius: 10, paddingHorizontal: 10, paddingVertical: 8, flexDirection: 'row', alignItems: 'center', gap: 5 } });
