// Local generated assets. Relative requires keep Metro resolution simple.
//
// Only *brand chrome* ships in the bundle now — logo lockups, the app mark and
// the food hero animation. All catalogue imagery (food items, products, store
// covers and banners) comes from the Aurasure API as `{ kind: 'uri' }` refs and
// renders through `SmartImage`; nothing content-related is bundled here anymore.
//
// Brand marks stay PNG because they need alpha, and because expo-splash-screen
// and the Android adaptive icon only accept PNG. All brand PNGs are generated by
// scripts/generate-brand.mjs — edit the geometry there, never the bitmaps.
export const Images = {
  // Horizontal lockup (mark + "Aurasure"). Aspect ~3.76:1 - always give it a
  // box with that ratio, or contentFit="contain".
  logo: require('../assets/images/logo_aurasure.png'),
  // Same lockup in white, for dark/gradient surfaces.
  logoLight: require('../assets/images/logo_aurasure_light.png'),
  // Square mark only. Use this anywhere the slot is square (avatars, 44pt
  // chips) - the wordmark squashes badly in a square box.
  logoMark: require('../assets/images/logo_mark.png'),
  logoMarkLight: require('../assets/images/logo_mark_light.png'),
  // Vertical lockup: mark over wordmark over tagline (splash / empty states).
  logoStacked: require('../assets/images/logo_aurasure_stacked.png'),
  // Food module hero animation (app chrome, not catalogue content).
  heroFoodGif: require('../assets/images/hero_food.gif'),
};
