// Local generated assets. Relative requires keep Metro resolution simple.
// Artwork ships as WebP (RGB, quality 78, Lanczos-downscaled to what the UI
// actually draws - nothing here renders wider than ~1024px); the logo stays PNG
// because expo-splash-screen and the Android adaptive icon need it.
export const Images = {
  logo: require('../assets/images/logo_aurasure.png'),
  bannerFood: require('../assets/images/banner_food.webp'),
  bannerShop: require('../assets/images/banner_shop.webp'),
  bannerSunglasses: require('../assets/images/banner_sunglasses.webp'),
  bannerAudio: require('../assets/images/banner_audio.webp'),
  foodBurger: require('../assets/images/food_burger.webp'),
  foodPizza: require('../assets/images/food_pizza.webp'),
  foodSalad: require('../assets/images/food_salad.webp'),
  foodDessert: require('../assets/images/food_dessert.webp'),
  foodBiryani: require('../assets/images/food_biryani.webp'),
  foodChowmein: require('../assets/images/food_chowmein.webp'),
  foodMomos: require('../assets/images/food_momos.webp'),
  foodIcecream: require('../assets/images/food_icecream.webp'),
  foodDosa: require('../assets/images/food_dosa.webp'),
  foodKebab: require('../assets/images/food_kebab.webp'),
  foodThali: require('../assets/images/food_thali.webp'),
  foodLitti: require('../assets/images/food_litti.webp'),
  foodFriedChicken: require('../assets/images/food_friedchicken.webp'),
  heroFoodGif: require('../assets/images/hero_food.gif'),
  shopHeadphones: require('../assets/images/shop_headphones.webp'),
  shopHeadphonesGray: require('../assets/images/shop_headphones_gray.webp'),
  shopWatch: require('../assets/images/shop_watch.webp'),
  shopSmartwatch: require('../assets/images/shop_smartwatch.webp'),
  shopLaptop: require('../assets/images/shop_laptop.webp'),
  shopPhone: require('../assets/images/shop_phone.webp'),
  shopCamera: require('../assets/images/shop_camera.webp'),
  shopEarbuds: require('../assets/images/shop_earbuds.webp'),
  shopDiffuser: require('../assets/images/shop_diffuser.webp'),
  shopSunglassesAviator: require('../assets/images/shop_sunglasses_aviator.webp'),
  shopSunglassesWayfarer: require('../assets/images/shop_sunglasses_wayfarer.webp'),
  shopSunglassesRetro: require('../assets/images/shop_sunglasses_retro.webp'),
  shopSunglassesSport: require('../assets/images/shop_sunglasses_sport.webp'),
  shopSunglassesBlue: require('../assets/images/shop_sunglasses_blue.webp'),
  shopSunglassesRose: require('../assets/images/shop_sunglasses_rose.webp'),
  shopSneakerWhite: require('../assets/images/shop_sneaker_white.webp'),
  shopSneakerRun: require('../assets/images/shop_sneaker_run.webp'),
  shopSneakerHigh: require('../assets/images/shop_sneaker_high.webp'),
  storeTitanium: require('../assets/images/store_titanium.webp'),
  storeSonce: require('../assets/images/store_sonce.webp'),
  storeNova: require('../assets/images/store_nova.webp'),
  storePulse: require('../assets/images/store_pulse.webp'),
  storeHearth: require('../assets/images/store_hearth.webp'),
  storeLumen: require('../assets/images/store_lumen.webp'),
  storeNorthwind: require('../assets/images/store_northwind.webp'),
  storeGrip: require('../assets/images/store_grip.webp'),
};
