import React, { useState } from 'react';
import { Alert, StyleSheet, View } from 'react-native';
import { useNavigation } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { Screen } from '@/components/ui/Screen';
import { Text } from '@/components/ui/Text';
import { Input } from '@/components/ui/Input';
import { Button } from '@/components/ui/Button';
import { Badge, Card, RowButton, SectionTitle } from '@/components/ui/VendorUI';
import { Icon } from '@/lib/icons';
import { useVendor } from '@/context/VendorContext';
import { vendorApi } from '@/api/vendor';
import { colors } from '@/theme/colors';
import { radius } from '@/theme/tokens';
import { haptic } from '@/lib/haptics';
import type { RootStackParamList } from '@/navigation/types';

type Nav = NativeStackNavigationProp<RootStackParamList>;
export function MoreScreen(): React.ReactElement { const { vendor, logout, refresh } = useVendor(); const navigation = useNavigation<Nav>(); const [issueOpen, setIssueOpen] = useState(false); const [title, setTitle] = useState(''); const [detail, setDetail] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const openIssues = vendor?.issues?.filter((issue) => issue.status !== 'resolved') ?? [];
  const submitIssue = async () => { if (title.trim().length < 3) { setMessage('Add a short issue title.'); return; } setBusy(true); try { await vendorApi.issue(title.trim(), detail.trim()); await refresh(); setTitle(''); setDetail(''); setIssueOpen(false); setMessage('Ticket sent to the Aurasure team.'); haptic.success(); } catch (e) { setMessage(e instanceof Error ? e.message : 'Could not send ticket'); haptic.error(); } finally { setBusy(false); } };
  return <Screen title="More" subtitle={vendor?.ownerName || vendor?.phone} onRefresh={() => void refresh()}>
    <Card tone="dark" style={styles.profile}><View style={styles.avatar}><Icon name="store" size={25} color={colors.brand[700]} /></View><View style={{ flex: 1, marginLeft: 12 }}><Text variant="h3" weight="bold" color={colors.white}>{vendor?.outletName || 'Your outlet'}</Text><Text variant="caption" color="#EAC9DA" style={{ marginTop: 3 }}>{vendor?.module === 'food' ? 'Food kitchen' : 'Shop'} · {vendor?.city || 'Location not set'}</Text></View><Badge label={vendor?.isOpen ? 'OPEN' : 'PAUSED'} color={vendor?.isOpen ? '#8BF0B5' : '#FBC77C'} background="rgba(255,255,255,.12)" /></Card>
    {vendor?.reviewNote && vendor.status !== 'approved' ? <Card tone="warm" style={{ marginTop: 12 }}><View style={styles.note}><Icon name="circleAlert" size={17} color={colors.warning} /><View style={{ flex: 1 }}><Text variant="caption" weight="bold" color={colors.warning}>ACTION FROM REVIEW TEAM</Text><Text variant="bodySm" style={{ marginTop: 4 }}>{vendor.reviewNote}</Text></View></View></Card> : null}
    <SectionTitle title="Manage outlet" /><Card style={styles.section}><RowButton icon="store" title="Outlet profile & hours" subtitle={vendor?.address || 'Add outlet details'} onPress={() => navigation.navigate('Outlet')} /><RowButton icon="mapPinned" title="Outlet map pin" subtitle="Dispatch uses this location" onPress={() => navigation.navigate('Map')} /><RowButton icon="chart" title="Business & payouts" subtitle="Sales, settlements and statements" onPress={() => navigation.navigate('Business')} /><RowButton icon="users" title="Staff access" subtitle="Add an orders-only team member" onPress={() => Alert.alert('Staff access', 'Staff accounts are managed securely from the web console in this build. Raise a ticket if you need one added.')} /></Card>
    <SectionTitle title="Support" action={openIssues.length ? `${openIssues.length} open` : undefined} /><Card style={styles.section}><RowButton icon="message" title="Raise an issue" subtitle="Payout, rider, menu or account help" onPress={() => { setIssueOpen((value) => !value); setMessage(''); }} /><RowButton icon="bell" title="Order alerts" subtitle="Keep notifications and sound enabled" onPress={() => Alert.alert('Order alerts', 'Aurasure will use your device notification settings for new order alerts. Enable notifications in system settings if you miss a ticket.')} /><RowButton icon="helpCircle" title="Help centre" subtitle="Guides for orders and outlet operations" onPress={() => Alert.alert('Help centre', 'Need a hand? Raise an issue and our team will reply on your account.')} /></Card>
    {issueOpen ? <Card style={styles.form}><Text variant="h3" weight="bold">Tell us what happened</Text><Input label="Issue title" value={title} onChangeText={setTitle} placeholder="Payout, rider, wrong menu…" leftIcon="circleAlert" /><Input label="Details" value={detail} onChangeText={setDetail} multiline placeholder="Include order code or dates if useful" />{message ? <Text variant="caption" color={message.startsWith('Ticket') ? colors.success : colors.danger} style={{ marginBottom: 10 }}>{message}</Text> : null}<Button title="Send support ticket" loading={busy} onPress={() => void submitIssue()} /></Card> : null}
    {openIssues.length ? <><SectionTitle title="Open tickets" />{openIssues.slice(0, 3).map((issue) => <Card key={issue.id} style={styles.issue}><View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}><Icon name="message" size={16} color={colors.warning} /><Text variant="title" weight="bold" style={{ flex: 1 }}>{issue.title}</Text><Badge label={issue.status.replace('_', ' ')} color={colors.warning} background={colors.warningBg} /></View><Text variant="caption" color={colors.textSecondary} style={{ marginTop: 6 }}>{issue.body}</Text></Card>)}</> : null}
    <SectionTitle title="Account" /><Card style={styles.section}><RowButton icon="refresh" title="Refresh profile" subtitle="Sync the latest status from server" onPress={() => void refresh()} /><RowButton icon="logout" title="Sign out" subtitle="Sign in again to manage this outlet" destructive onPress={() => Alert.alert('Sign out?', 'You will need to sign in again to manage orders.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Sign out', style: 'destructive', onPress: logout }])} /></Card><Text variant="caption" color={colors.textTertiary} style={{ textAlign: 'center', marginTop: 22 }}>Aurasure Vendor · secure outlet operations</Text>
  </Screen>; }
const styles = StyleSheet.create({ profile: { flexDirection: 'row', alignItems: 'center', padding: 16, borderWidth: 0 }, avatar: { width: 52, height: 52, borderRadius: 17, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center' }, section: { paddingHorizontal: 13, paddingVertical: 3 }, note: { flexDirection: 'row', gap: 9 }, form: { marginTop: 10 }, issue: { marginBottom: 8 }, });
