import React from 'react';
import { Pressable, StyleSheet, View } from 'react-native';
import { useNavigation } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { Screen } from '@/components/ui/Screen';
import { Text } from '@/components/ui/Text';
import { Badge, Card, Divider, RowButton, SectionTitle } from '@/components/ui/VendorUI';
import { Icon } from '@/lib/icons';
import { useVendor } from '@/context/VendorContext';
import { colors } from '@/theme/colors';
import { radius } from '@/theme/tokens';
import type { RootStackParamList } from '@/navigation/types';
import { useVendorModal } from '@/components/ui/VendorModal';

type Nav = NativeStackNavigationProp<RootStackParamList>;
export function MoreScreen(): React.ReactElement { const { showModal } = useVendorModal(); const { vendor, logout, refresh } = useVendor(); const navigation = useNavigation<Nav>(); const openIssues = vendor?.issues?.filter((issue) => issue.status !== 'resolved') ?? [];
  return <Screen title="More" subtitle={vendor?.ownerName || vendor?.phone} onRefresh={() => void refresh()}>
    <Card tone="dark" style={styles.profile}><View style={styles.avatar}><Icon name="store" size={25} color={colors.brand[700]} /></View><View style={{ flex: 1, marginLeft: 12 }}><Text variant="h3" weight="bold" color={colors.white}>{vendor?.outletName || 'Your outlet'}</Text><Text variant="caption" color="#EAC9DA" style={{ marginTop: 3 }}>{vendor?.module === 'food' ? 'Food kitchen' : 'Shop'} · {vendor?.city || 'Location not set'}</Text></View><Badge label={vendor?.isOpen ? 'OPEN' : 'PAUSED'} color={vendor?.isOpen ? '#8BF0B5' : '#FBC77C'} background="rgba(255,255,255,.12)" /></Card>
    {vendor?.reviewNote && vendor.status !== 'approved' ? <Card tone="warm" style={{ marginTop: 12 }}><View style={styles.note}><Icon name="circleAlert" size={17} color={colors.warning} /><View style={{ flex: 1 }}><Text variant="caption" weight="bold" color={colors.warning}>ACTION FROM REVIEW TEAM</Text><Text variant="bodySm" style={{ marginTop: 4 }}>{vendor.reviewNote}</Text></View></View></Card> : null}
    <SectionTitle title="Manage outlet" /><Card style={styles.section}><RowButton icon="store" title="Outlet profile & hours" subtitle={vendor?.address || 'Add outlet details'} onPress={() => navigation.navigate('Outlet')} /><RowButton icon="mapPinned" title="Outlet map pin" subtitle="Dispatch uses this location" onPress={() => navigation.navigate('Map')} /><RowButton icon="chart" title="Business & payouts" subtitle="Sales, settlements and statements" onPress={() => navigation.navigate('Business')} /><RowButton icon="users" title="Staff access" subtitle={vendor?.staff?.length ? `${vendor.staff.length} team member${vendor.staff.length === 1 ? '' : 's'} with order access` : 'Add an orders-only team member'} onPress={() => navigation.navigate('Staff')} /></Card>
    <SectionTitle title="Support" action={openIssues.length ? `${openIssues.length} open` : undefined} /><Card style={styles.section}><RowButton icon="message" title="Raise an issue" subtitle="Payout, rider, menu or account help" onPress={() => navigation.navigate('Tickets')} /><RowButton icon="bell" title="Order alerts" subtitle="Live board refreshes every 15 seconds" onPress={() => navigation.navigate('Alerts')} /><RowButton icon="helpCircle" title="Help centre" subtitle="Guides for orders and outlet operations" onPress={() => navigation.navigate('Help')} /></Card>
    {openIssues.length ? <><SectionTitle title="Open tickets" action="View all" onAction={() => navigation.navigate('Tickets')} /><Card style={styles.section}>{openIssues.slice(0, 3).map((issue, index) => <React.Fragment key={issue.id}>{index ? <Divider /> : null}<Pressable onPress={() => navigation.navigate('Tickets')} style={styles.issue}><View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}><Icon name="message" size={16} color={colors.warning} /><Text variant="bodySm" weight="bold" style={{ flex: 1 }}>{issue.title}</Text><Badge label={issue.status.replace('_', ' ')} color={colors.warning} background={colors.warningBg} /></View>{issue.body ? <Text variant="caption" color={colors.textSecondary} style={{ marginTop: 5 }} numberOfLines={2}>{issue.body}</Text> : null}</Pressable></React.Fragment>)}</Card></> : null}
    <SectionTitle title="Account" /><Card style={styles.section}><RowButton icon="refresh" title="Refresh profile" subtitle="Sync the latest status from server" onPress={() => void refresh()} /><RowButton icon="logout" title="Sign out" subtitle="Sign in again to manage this outlet" destructive onPress={() => showModal({ title: 'Sign out?', message: 'You will need to sign in again to manage orders.', actions: [{ label: 'Cancel', secondary: true }, { label: 'Sign out', destructive: true, onPress: logout }] })} /></Card><Text variant="caption" color={colors.textTertiary} style={{ textAlign: 'center', marginTop: 22 }}>Aurasure Vendor · secure outlet operations</Text>
  </Screen>; }
const styles = StyleSheet.create({ profile: { flexDirection: 'row', alignItems: 'center', padding: 16, borderWidth: 0 }, avatar: { width: 52, height: 52, borderRadius: 17, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center' }, section: { paddingHorizontal: 13, paddingVertical: 3 }, note: { flexDirection: 'row', gap: 9 }, issue: { paddingVertical: 12 }, });
