import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Alert, FlatList, Pressable, StyleSheet, View } from 'react-native';
import { useNavigation } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { Screen } from '@/components/ui/Screen';
import { Text } from '@/components/ui/Text';
import { Button } from '@/components/ui/Button';
import { Badge, Card, EmptyState, IconButton, SectionTitle } from '@/components/ui/VendorUI';
import { Icon } from '@/lib/icons';
import { vendorApi, type OrderStatus, type VendorOrder } from '@/api/vendor';
import { colors } from '@/theme/colors';
import { radius, spacing } from '@/theme/tokens';
import { haptic } from '@/lib/haptics';
import type { RootStackParamList } from '@/navigation/types';

type Nav = NativeStackNavigationProp<RootStackParamList>;
const TABS: { key: string; label: string; statuses: OrderStatus[] }[] = [
  { key: 'new', label: 'New', statuses: ['placed'] },
  { key: 'preparing', label: 'Preparing', statuses: ['confirmed', 'preparing'] },
  { key: 'ready', label: 'Ready', statuses: ['out_for_delivery'] },
  { key: 'completed', label: 'Completed', statuses: ['delivered', 'cancelled'] },
];
const STATUS: Record<OrderStatus, { label: string; color: string; bg: string }> = {
  placed: { label: 'New', color: colors.info, bg: colors.infoBg }, confirmed: { label: 'Accepted', color: colors.brand[700], bg: colors.brand[50] }, preparing: { label: 'Preparing', color: colors.warning, bg: colors.warningBg }, out_for_delivery: { label: 'Ready', color: colors.success, bg: colors.successBg }, delivered: { label: 'Completed', color: colors.success, bg: colors.successBg }, cancelled: { label: 'Cancelled', color: colors.danger, bg: colors.dangerBg },
};
function money(v: number): string { return `₹${Math.round(v).toLocaleString('en-IN')}`; }
function age(iso: string): string { const minutes = Math.max(0, Math.floor((Date.now() - new Date(iso).getTime()) / 60000)); return minutes < 1 ? 'Just now' : `${minutes}m ago`; }
function Countdown({ placedAt }: { placedAt: string }): React.ReactElement { const [now, setNow] = useState(Date.now()); useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 30000); return () => clearInterval(timer); }, []); const left = Math.max(0, 15 - Math.floor((now - new Date(placedAt).getTime()) / 60000)); return <View style={styles.countdown}><View style={styles.countRing}><Text variant="caption" weight="bold" color={left < 5 ? colors.danger : colors.info}>{left}m</Text></View><Text variant="caption" weight="bold" color={left < 5 ? colors.danger : colors.info}>to accept</Text></View>; }
function OrderCard({ order, onOpen, onAccept, onReject, onReady, acting }: { order: VendorOrder; onOpen: () => void; onAccept: () => void; onReject: () => void; onReady: () => void; acting: boolean }): React.ReactElement { const sc = STATUS[order.status]; const isNew = order.status === 'placed'; const items = order.items.map((item) => `${item.qty}× ${item.name}`).join(' · '); return <Card style={[styles.orderCard, isNew && styles.newCard]}><Pressable onPress={onOpen}><View style={styles.orderTop}><View style={styles.code}><View style={[styles.orderIcon, { backgroundColor: sc.bg }]}><Icon name={isNew ? 'zap' : 'receipt'} size={18} color={sc.color} /></View><View><View style={{ flexDirection: 'row', alignItems: 'center', gap: 7 }}><Text variant="h3" weight="bold">#{order.code}</Text><Badge label={sc.label} color={sc.color} background={sc.bg} /></View><Text variant="caption" color={colors.textSecondary} style={{ marginTop: 3 }}>{order.customer?.name || order.user?.name || 'Customer'} · {age(order.placedAt)}</Text></View></View>{isNew ? <Countdown placedAt={order.placedAt} /> : <IconButton icon="chevronRight" size={34} color={colors.textTertiary} background={colors.surfaceAlt} />}</View><Text variant="body" color={colors.text} style={{ marginTop: 14 }} numberOfLines={2}>{items || 'No item details'}</Text><View style={styles.orderMeta}><View style={styles.meta}><Icon name="package" size={15} color={colors.textSecondary} /><Text variant="caption" color={colors.textSecondary}>{order.items.reduce((sum, item) => sum + item.qty, 0)} items</Text></View><View style={styles.meta}><Icon name="wallet" size={15} color={colors.textSecondary} /><Text variant="caption" color={colors.textSecondary}>{order.payBy?.toUpperCase() || 'COD'}</Text></View><Text variant="title" weight="bold" color={colors.brand[700]}>{money(order.total)}</Text></View>{order.instructions ? <View style={styles.note}><Icon name="info" size={14} color={colors.warning} /><Text variant="caption" color={colors.warning} numberOfLines={1} style={{ flex: 1 }}>{order.instructions}</Text></View> : null}</Pressable>{isNew ? <View style={styles.actions}><Button title="Reject" variant="secondary" size="sm" fullWidth={false} onPress={onReject} disabled={acting} style={{ flex: 1 }} /><Button title={acting ? 'Accepting…' : 'Accept order'} size="sm" onPress={onAccept} disabled={acting} style={{ flex: 1 }} /></View> : order.status === 'preparing' || order.status === 'confirmed' ? <Button title="Mark ready for pickup" size="sm" onPress={onReady} loading={acting} style={{ marginTop: 13 }} /> : order.delivery?.pickupOtp ? <View style={styles.otp}><Icon name="bike" size={16} color={colors.brand[700]} /><Text variant="caption" weight="bold" color={colors.brand[700]}>Pickup OTP {order.delivery.pickupOtp}</Text><Text variant="caption" color={colors.textSecondary} style={{ marginLeft: 'auto' }}>{order.delivery.riderName || 'Waiting for rider'}</Text></View> : null}</Card>; }

export function OrdersScreen(): React.ReactElement {
  const navigation = useNavigation<Nav>(); const [tab, setTab] = useState('new'); const [orders, setOrders] = useState<VendorOrder[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState(''); const [acting, setActing] = useState('');
  const load = useCallback(async (silent = false) => { if (!silent) setLoading(true); try { const result = await vendorApi.orders(); setOrders(result.orders); setError(''); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load order board'); } finally { setLoading(false); setRefreshing(false); } }, []);
  useEffect(() => { void load(); const timer = setInterval(() => void load(true), 15000); return () => clearInterval(timer); }, [load]);
  const tabData = useMemo(() => TABS.find((item) => item.key === tab) ?? TABS[0]!, [tab]); const visible = orders.filter((order) => tabData.statuses.includes(order.status)); const count = (key: string) => { const def = TABS.find((item) => item.key === key); return orders.filter((order) => def?.statuses.includes(order.status)).length; };
  const run = async (order: VendorOrder, action: () => Promise<unknown>) => { setActing(order.id); try { await action(); await load(true); haptic.success(); } catch (e) { Alert.alert('Could not update order', e instanceof Error ? e.message : 'Try again'); haptic.error(); } finally { setActing(''); } };
  const accept = (order: VendorOrder) => { const choices = [10, 15, 20, 30].map((minutes) => ({ text: `${minutes} minutes`, onPress: () => void run(order, () => vendorApi.accept(order.id, minutes, order.status)) })); choices.push({ text: 'Cancel', onPress: () => undefined }); Alert.alert('Set prep time', 'How long will this order take?', choices as any); };
  const reject = (order: VendorOrder) => Alert.alert('Reject this order?', 'The customer will be notified. Choose a reason.', [{ text: 'Item unavailable', onPress: () => void run(order, () => vendorApi.reject(order.id, 'item_unavailable', undefined, order.status)) }, { text: 'Kitchen busy', onPress: () => void run(order, () => vendorApi.reject(order.id, 'kitchen_busy', undefined, order.status)) }, { text: 'Keep order', style: 'cancel' }]);
  return <Screen title="Order board" subtitle={count('new') ? `${count('new')} new ticket${count('new') > 1 ? 's' : ''} need attention` : 'Keep every ticket moving'} scroll={false} padded={false} headerRight={<IconButton icon="refresh" color={colors.brand[700]} onPress={() => { setRefreshing(true); void load(); }} />}>
    <View style={styles.tabs}>{TABS.map((item) => { const active = item.key === tab; const n = count(item.key); return <Pressable key={item.key} onPress={() => { setTab(item.key); haptic.selection(); }} style={[styles.tab, active && styles.activeTab]}><Text variant="caption" weight="bold" color={active ? colors.white : colors.textSecondary}>{item.label}</Text>{n > 0 ? <View style={[styles.tabCount, active && { backgroundColor: 'rgba(255,255,255,.22)' }]}><Text variant="caption" weight="bold" color={active ? colors.white : colors.brand[700]}>{n > 99 ? '99+' : n}</Text></View> : null}</Pressable>; })}</View>
    {error ? <View style={styles.error}><Icon name="wifi" size={16} color={colors.warning} /><Text variant="caption" color={colors.warning} style={{ flex: 1 }}>{error}</Text><Pressable onPress={() => void load()}><Text variant="caption" weight="bold" color={colors.warning}>Retry</Text></Pressable></View> : null}
    {loading ? <View style={styles.center}><Text variant="body" color={colors.textSecondary}>Loading order board…</Text></View> : <FlatList data={visible} keyExtractor={(item) => item.id} contentContainerStyle={[styles.list, !visible.length && { flex: 1 }]} showsVerticalScrollIndicator={false} onRefresh={() => { setRefreshing(true); void load(); }} refreshing={refreshing} renderItem={({ item }) => <OrderCard order={item} acting={acting === item.id} onOpen={() => navigation.navigate('OrderDetail', { orderId: item.id })} onAccept={() => accept(item)} onReject={() => reject(item)} onReady={() => void run(item, () => vendorApi.ready(item.id, item.status))} />} ListEmptyComponent={<EmptyState icon={tab === 'new' ? 'zap' : tab === 'completed' ? 'receipt' : 'timer'} title={tab === 'new' ? 'No new orders' : `No ${tab} tickets`} body={tab === 'new' ? 'You’re open. We’ll alert you as soon as a customer places an order.' : 'Tickets move here automatically as your team works.'} />} />}
  </Screen>;
}
const styles = StyleSheet.create({ tabs: { flexDirection: 'row', gap: 5, paddingHorizontal: 4, paddingVertical: 9, backgroundColor: colors.surface, borderBottomWidth: 1, borderColor: colors.border }, tab: { flex: 1, minHeight: 40, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 5 }, activeTab: { backgroundColor: colors.brand[600] }, tabCount: { minWidth: 18, height: 18, borderRadius: 9, paddingHorizontal: 4, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.brand[50] }, list: { paddingHorizontal: 4, paddingTop: 10, paddingBottom: 28 }, orderCard: { marginBottom: 10, padding: 14 }, newCard: { borderColor: colors.info, borderWidth: 1.5 }, orderTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, code: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 }, orderIcon: { width: 40, height: 40, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, countdown: { alignItems: 'center', gap: 3 }, countRing: { width: 44, height: 44, borderRadius: 22, borderWidth: 3, borderColor: colors.info, alignItems: 'center', justifyContent: 'center' }, orderMeta: { flexDirection: 'row', alignItems: 'center', gap: 13, marginTop: 13, paddingTop: 11, borderTopWidth: 1, borderColor: colors.border }, meta: { flexDirection: 'row', alignItems: 'center', gap: 4 }, note: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 10, padding: 9, backgroundColor: colors.warningBg, borderRadius: 8 }, actions: { flexDirection: 'row', gap: 8, marginTop: 13 }, otp: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 13, padding: 10, borderRadius: 9, backgroundColor: colors.brand[50] }, error: { marginHorizontal: 4, marginTop: 8, padding: 10, backgroundColor: colors.warningBg, flexDirection: 'row', gap: 7, alignItems: 'center', borderRadius: 9 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' } });
